name: Github Actions
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      -  name: Pring Greetings
         run: echo "hello world"
      -  name: Pring goodbye
         run: echo "Done - bye!"
